name: Update PR Label
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update_label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update PR Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const criticalFilePathEndsWith = [
              "common/models.py",
              "swiggy.py",
              "zomato.py",
              "talabat.py",
              ];
            const resp = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            let files = resp.data;
            files = files.filter((file) => {
              return criticalFilePathEndsWith.some((filepath) => {
                return file.filename.endsWith(filepath);
              });
            });
            const labels = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const labelExists = labels.data.some((label) => {
              return label.name === 'critical';
            });
            if (files.length > 0) {
              if (!labelExists) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: ['critical']
                });
              }
            } else {
              if (labelExists) {
                await github.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'critical'
                });
              }
            }
